### ISSUE TITLE
not able to extract comments from n38 file

### ISSUE THREAD

**Issue by sanjaykmenon** [obrl-soil/em38#1]
hello!! first off, thank you very much for building this package. This works fantastic!

i wanted to point out that i'm not able to extract any comments i made on readings while recording them on the allegro mx. I didn't find anything in the package documentation that explicitly called it out. Can you tell me if there's a functionality available already or it needs to be worked on?

Thanks once again for creating this! It has been a lifesaver.!

**Comment by obrl-soil** [comment]
Hi, thanks for your note :) I haven't had access to any n38 files that contain comments so I haven't been able to build that functionality properly yet. Are you willing to share any files with me that I could use for testing?

**Comment by sanjaykmenon** [comment]
Sure thing. I'm not able to attach the n38 file here for some reason?.

Here's a google drive link with a sample.

https://drive.google.com/drive/folders/1fceRwapJVHGE3a6Ik3MGU3Y_K4-QJAV8?usp=sharing

**Comment by obrl-soil** [comment]
Awesome, thanks! Ok, I think I've found a solution that adds in comments to the output survey lines. Try installing the dev version (0.0.2) and see if it works for you.

**Comment by obrl-soil** [comment]
I'm assuming this fix was adequate, let me know if not
